apiVersion: v2
name: pcq-frontend
description: A Helm chart for the HMCTS PCQ product
home: https://github.com/hmcts/pcq-frontend
version: 1.2.6
maintainers:
  - name: HMCTS PCQ Team
    email: pcq-action-group@HMCTS.NET
dependencies:
  - name: nodejs
    version: 2.0.1
    repository: '@hmctspublic'
  - name: redis
    version: 10.5.7
    repository: '@stable'
    condition: redis.enabled
