nodejs:
  environment:
    NODE_ENV: "preview"
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    REDIS_USE_TLS: false
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  livenessProbe:
    enabled: true
    httpGet:
      path: /health/liveness
      port: 4000
    initialDelaySeconds: 30
    periodSeconds: 15
    successThreshold: 1
    timeoutSeconds: 3
    failureThreshold: 3
  readinessProbe:
    enabled: true
    httpGet:
      path: /health/livenes
      port: 4000
    initialDelaySeconds: 30
    periodSeconds: 15
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 

redis:
  enabled: true
