nodejs:
  environment:
    REDIS_HOST: ${SERVICE_NAME}-redis-master
    REDIS_PORT: 6379
    REDIS_USE_TLS: false
    PCQ_BACKEND_URL: http://pcq-backend-pr-561-java
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}

redis:
  enabled: true
