nodejs:
  applicationPort: 4000
  memoryRequests: "512Mi"
  cpuRequests: "100m"
  memoryLimits: "1024Mi"
  cpuLimits: "500m"
  environment:
    PUBLIC_PROTOCOL: https
    REFORM_TEAM: pcq
    REFORM_SERVICE_NAME: pcq-frontend
    S2S_URL:
    VALIDATION_SERVICE_URL:
    SUBMIT_SERVICE_URL:
    ORCHESTRATION_SERVICE_URL:
    REFORM_ENVIRONMENT: aat
  image: hmctspublic.azurecr.io/pcq/pcq-frontend:latest
  aadIdentityName: pcq

  keyVaults:
    pcq:
      resourceGroup: pcq
      secrets:
        - AppInsightsInstrumentationKey

redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false
