# This is used in E2E testing
appName: 'frontend'
project: 'pcq'
version: 'x.x-laptop'
deployment_env: 'local'
environment: 'test'

service:
  name: 'pcq-frontend'

featureToggles:
  enabled: false
  ft_test: 'test'

tokenKeys:
  notregistered: 'SERVICE_TOKEN_KEY'

testUrl: 'http://localhost:4000'

saucelabs:
  browser: 'chrome'
  username: 'username'
  key: 'privatekey'
  tunnelId: 'reformtunnel'
  waitForTimeout: 10000
  smartWait: 5000

showSitemap: true

http:
  port: 3001

session:
  expires: 10000 # ms
  ttl: 60 # s

features:
  idam: false
